version: '3'

services:
  rtsp-server:
    build: .
    ports:
      - "8554:8554"
    volumes:
      - ./config.json:/app/config.json
    restart: unless-stopped
    environment:
      - CONFIG_PATH=/app/config.json
