name: ai_example
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pytest=8.1.1
  - black=24.2.0
  - ipykernel=6.29.3
  - jupyter=1.0.0
  - notebook=7.1.3
  - pip:
    - isort==5.13.2
    - mypy==1.9.0
    - python-dotenv==1.0.1 